### ISSUE TITLE
lubuntu系メモ

### ISSUE THREAD

**Issue by aaya-pb** [folipop/linux#1]
#### Ubuntu14.04LTSをCUIで起動する方法

http://note.kurodigi.com/ubuntu1404-cuilaunch/
#### LinuxのUbuntuでシステムをシャットダウン・再起動するコマンド

http://www.miuxmiu.com/archives/2011/03/19/linux_ubuntu_system_shutdown_restart_command.html
#### Ubuntuの英語環境をCUIにて日本語対応にする

http://jlinuxer.dip.jp/?p=551
うまく行かず
#### Debian(Ubuntu)で コンソールに日本語表示してみた

http://server-setting.info/debian/debian-console-japanease.html

**Comment by aaya-pb** [comment]
## update

#### Lubuntu 13.04 の apt-get install で「Not Found」となる現象への対処

http://ranosgrant.cocolog-nifty.com/blog/2014/07/lubuntu-1304-ap.html

すごく役にたった

```
 対処方法

1. /etc/apt/sources.list の中の URL のサイトを old-releases.ubuntu.com に変更します。

以下のコマンドで一括変換してしまいます。
（実行前に /etc/apt/sources.list をどこかにコピーして変更前の内容を退避しておくと良いでしょう）
$ sudo cp /etc/apt/sources.list /etc/apt/sources.list.old
$ sudo sed -i -e 's|//.*ubuntu.com/|//old-releases.ubuntu.com/|' /etc/apt/sources.list
2. 以下のコマンドで情報を更新します。

$ sudo apt-get update
```

**Comment by aaya-pb** [comment]
## Editor

#### GNU nanoの使い方Add Star

http://d.hatena.ne.jp/satake7/20080211/1207807040

```
　・Ctrl+O　ファイルSAVE
　・Ctrl+X　終了
　・Ctrl+^　マーク(選択開始)
　・Ctrl+K　カット(選択終了)。Ctrl+^で選択してCtrl+Kでカット。コピーはわからず。
　・Ctrl+U　ペースト
　・Ctrl+W　検索。次を検索はわからず。
　・Ctrl+D　DEL(カーソルの文字を削除)。DELキーはBSキーになる。
```

**Comment by blueb901** [comment]
test
